version: '3.2'
services:
  ds_test:
    container_name: ds_test
    build:
      context: .
      dockerfile: Dockerfile.ds_test
    volumes:
      - ./testscript:/testscript
    environment:
      - QUEUE_HOST=${QUEUE_HOST}
    tty: true
networks:
  default:
    external:
      name: ds_opal_opal_net