version: '3.2'
services:
  ds_test:
    container_name: ds_test
    image: docker.miracum.org/datashield_miracum/ds_test:v0.6.0
    ##build:
     # context: .
      #dockerfile: Dockerfile.ds_test
    volumes:
      - ./testscript:/testscript
    environment:
      - QUEUE_HOST=${QUEUE_HOST}
    tty: true
    command: bash -c "tail -f /dev/null" 
networks:
  default:
    external:
      name: ds_opal_opal_net